version: "3.8"

services:
  xdc-node-erigon-testnet:
    image: anilchinchawale/erix:latest
    container_name: xdc-node-erigon-testnet
    restart: unless-stopped
    ports:
      - "127.0.0.1:8547:8545"
      - "0.0.0.0:30304:30304"
      - "0.0.0.0:30304:30304/udp"
    volumes:
      - erigon-testnet-data:/home/erigon/.local/share/erigon
    entrypoint: ["/usr/local/bin/erigon"]
    command:
      - --datadir=/home/erigon/.local/share/erigon
      - --chain=xdc-apothem
      - --networkid=51
      - --port=30304
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api=eth,net,web3,txpool,debug,erigon,admin
      - --maxpeers=50
      - --bootnodes=enode://10f494ec14b098f712bc46d548b3ee774d6e3bb460e4ced49f88b78f119ff56c290525e7ffcbb8ec4dbe28817944a6d6871f70c88a9b2e991b415f5d3d87ae53@157.173.120.219:30312
      - --verbosity=3
    networks:
      - xdc-network

  xdc-agent-erigon-testnet:
    image: anilchinchawale/erix:latest
    platform: linux/amd64
    container_name: xdc-agent-erigon-testnet
    restart: unless-stopped
    ports:
      - "0.0.0.0:7071:3000"
    volumes:
      - ../testnet/.xdc-node/skynet-erigon.conf:/etc/xdc-node/skynet.conf
      - /proc:/host/proc:ro
    environment:
      - RPC_URL=http://xdc-node-erigon-testnet:8545
      - NODE_RPC_PORT=8545
      - DASHBOARD_AUTH_ENABLED=false
    depends_on:
      - xdc-node-erigon-testnet
    networks:
      - xdc-network

volumes:
  erigon-testnet-data:

networks:
  xdc-network:
    external: true
    name: docker_xdc-network
