#cloud-config
# XDC Node Setup - Cloud-Init Configuration
# Generated by Terraform xdc-node module

package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose
  - curl
  - jq
  - htop
  - fail2ban
  - ufw
  - unattended-upgrades

groups:
  - docker

users:
  - name: ubuntu
    groups: docker, sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
%{ for key in ssh_keys ~}
      - ${key}
%{ endfor ~}

write_files:
  - path: /etc/xdc/config.env
    permissions: '0644'
    content: |
      XDC_NETWORK=${network}
      XDC_CLIENT=${client}
      XDC_NODE_TYPE=${node_type}
      XDC_NODE_NAME=${node_name}
      XDC_RPC_ENABLED=${rpc_enabled}
      XDC_WS_ENABLED=${ws_enabled}
      XDC_METRICS_ENABLED=${metrics_enabled}
%{ if bootnodes != "" ~}
      XDC_BOOTNODES=${bootnodes}
%{ endif ~}
%{ if length(extra_flags) > 0 ~}
      XDC_EXTRA_FLAGS="${join(" ", extra_flags)}"
%{ endif ~}

  - path: /etc/xdc/docker-compose.yml
    permissions: '0644'
    content: |
      version: '3.8'
      services:
        xdc-node:
          container_name: xdc-node
          image: ${client == "XDPoSChain" ? "xinfin/xdc-node:latest" : "xinfinorg/erigon-xdc:latest"}
          restart: unless-stopped
          ports:
            - "30303:30303/tcp"
            - "30303:30303/udp"
%{ if rpc_enabled ~}
            - "8545:8545"
%{ endif ~}
%{ if ws_enabled ~}
            - "8546:8546"
%{ endif ~}
%{ if metrics_enabled ~}
            - "6060:6060"
%{ endif ~}
          volumes:
            - /data/xdc:/xdcchain
          environment:
            - NETWORK=${network}
            - NODE_NAME=${node_name}
          command: >
%{ if client == "XDPoSChain" ~}
            --${network}
            --datadir=/xdcchain
            --port=30303
%{ if rpc_enabled ~}
            --http
            --http.addr=0.0.0.0
            --http.port=8545
            --http.api=eth,net,web3,txpool
            --http.corsdomain=*
            --http.vhosts=*
%{ endif ~}
%{ if ws_enabled ~}
            --ws
            --ws.addr=0.0.0.0
            --ws.port=8546
            --ws.api=eth,net,web3
            --ws.origins=*
%{ endif ~}
%{ if metrics_enabled ~}
            --metrics
            --metrics.addr=0.0.0.0
            --metrics.port=6060
%{ endif ~}
%{ else ~}
            --chain=${network}
            --datadir=/data/erigon
            --port=30303
%{ if rpc_enabled ~}
            --http
            --http.addr=0.0.0.0
            --http.port=8545
            --http.api=eth,net,web3,txpool,trace,debug
            --http.corsdomain=*
            --http.vhosts=*
%{ endif ~}
%{ if ws_enabled ~}
            --ws
%{ endif ~}
%{ if metrics_enabled ~}
            --metrics
            --metrics.addr=0.0.0.0
            --metrics.port=6060
%{ endif ~}
%{ endif ~}
%{ for flag in extra_flags ~}
            ${flag}
%{ endfor ~}

  - path: /usr/local/bin/xdc-status
    permissions: '0755'
    content: |
      #!/bin/bash
      echo "=== XDC Node Status ==="
      echo "Network: ${network}"
      echo "Client: ${client}"
      echo "Node Type: ${node_type}"
      echo ""
      echo "=== Sync Status ==="
      curl -s -X POST -H "Content-Type: application/json" \
        --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' \
        http://localhost:8545/ | jq .
      echo ""
      echo "=== Peer Count ==="
      curl -s -X POST -H "Content-Type: application/json" \
        --data '{"jsonrpc":"2.0","method":"net_peerCount","params":[],"id":1}' \
        http://localhost:8545/ | jq -r '.result | tonumber'
      echo ""
      echo "=== Block Number ==="
      curl -s -X POST -H "Content-Type: application/json" \
        --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' \
        http://localhost:8545/ | jq -r '.result | tonumber'

  - path: /etc/systemd/system/xdc-node.service
    permissions: '0644'
    content: |
      [Unit]
      Description=XDC Node
      After=docker.service
      Requires=docker.service
      
      [Service]
      Type=simple
      WorkingDirectory=/etc/xdc
      ExecStart=/usr/bin/docker-compose up
      ExecStop=/usr/bin/docker-compose down
      Restart=always
      RestartSec=10
      
      [Install]
      WantedBy=multi-user.target

runcmd:
  # Enable and start Docker
  - systemctl enable docker
  - systemctl start docker
  
  # Configure firewall
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow ssh
  - ufw allow 30303/tcp
  - ufw allow 30303/udp
%{ if rpc_enabled ~}
  - ufw allow 8545/tcp
%{ endif ~}
%{ if ws_enabled ~}
  - ufw allow 8546/tcp
%{ endif ~}
%{ if metrics_enabled ~}
  - ufw allow 6060/tcp
%{ endif ~}
  - ufw --force enable
  
  # Create data directory
  - mkdir -p /data/xdc
  - chown -R ubuntu:ubuntu /data/xdc
  - chmod -R 755 /data/xdc
  
  # Enable fail2ban
  - systemctl enable fail2ban
  - systemctl start fail2ban
  
  # Enable automatic security updates
  - systemctl enable unattended-upgrades
  - systemctl start unattended-upgrades
  
  # Start XDC node
  - systemctl daemon-reload
  - systemctl enable xdc-node
  - systemctl start xdc-node
  
  # Install XNS CLI
  - |
    cd /opt
    if [ ! -d "/opt/xdc-node-setup" ]; then
      git clone https://github.com/XDCIndia/xdc-node-setup.git xdc-node-setup || true
    fi
    if [ -f "/opt/xdc-node-setup/cli/install.sh" ]; then
      bash /opt/xdc-node-setup/cli/install.sh
    fi
  
  # Log completion
  - echo "XDC Node setup completed at $(date)" >> /var/log/xdc-setup.log

final_message: "XDC Node ${node_name} setup complete. Network: ${network}, Client: ${client}"
