#!/bin/bash
# GP5 Deployment Standard - XNS Integration
# This file adds GP5 deployment standard functions to the XDC CLI

# GP5 Standard Configuration
readonly GP5_SKYNET_URL="https://net.xdc.network"
readonly GP5_SKYNET_API_KEY="master"
readonly GP5_ETHSTATS_SERVER="stats.xdcindia.com:3000"
readonly GP5_VERSION="v34"

# Generate SkyNet agent script for a node
generate_skynet_agent() {
    local node_name="$1"
    local rpc_port="${2:-8545}"
    local network="${3:-mainnet}"
    local output_dir="${4:-/opt/xdc-node/skynet}"
    
    mkdir -p "$output_dir"
    
    cat > "${output_dir}/skynet-agent-${node_name}.sh" << 'AGENT_EOF'
#!/bin/bash
# Auto-generated SkyNet agent for NODE_NAME_PLACEHOLDER
# Generated by XDC CLI GP5 Deployment Standard

NODE_NAME="NODE_NAME_PLACEHOLDER"
NETWORK="NETWORK_PLACEHOLDER"
RPC_URL="http://127.0.0.1:RPC_PORT_PLACEHOLDER"
SKYNET_URL="SKYNET_URL_PLACEHOLDER"
API_KEY="SKYNET_API_KEY_PLACEHOLDER"

# State file for persistence
STATE_FILE="OUTPUT_DIR_PLACEHOLDER/.skynet-state-NODE_NAME_PLACEHOLDER.json"

# Load or initialize node ID
load_node_id() {
    if [[ -f "$STATE_FILE" ]]; then
        jq -r '.nodeId // ""' "$STATE_FILE" 2>/dev/null
    fi
}

# Save node ID
save_node_id() {
    local node_id="$1"
    echo "{\"nodeId\":\"$node_id\",\"name\":\"$NODE_NAME\",\"registered\":\"$(date -Iseconds)\"}" > "$STATE_FILE"
}

# Register with SkyNet
register_node() {
    local node_info
    node_info=$(curl -s -m 10 -X POST "$RPC_URL" \
        -H 'Content-Type: application/json' \
        -d '{"jsonrpc":"2.0","method":"admin_nodeInfo","params":[],"id":1}' 2>/dev/null)
    
    local enode=$(echo "$node_info" | jq -r '.result.enode // ""')
    local version=$(echo "$node_info" | jq -r '.result.name // "Unknown"')
    local ipv4=$(curl -s -4 --max-time 2 https://ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')
    local chain_id=CHAIN_ID_PLACEHOLDER
    
    local payload=$(cat << PAYLOAD_EOF
{
    "name":"$NODE_NAME",
    "host":"$ipv4",
    "role":"fullnode",
    "rpcUrl":"$RPC_URL",
    "enode":"$enode",
    "clientType":"gp5",
    "client":"gp5",
    "network":"$NETWORK",
    "chainId":$chain_id,
    "version":"$version"
}
PAYLOAD_EOF
)
    
    local resp
    resp=$(curl -s -m 15 -X POST "${SKYNET_URL}/api/nodes/register" \
        -H 'Content-Type: application/json' \
        -H "X-API-Key: $API_KEY" \
        -d "$payload" 2>/dev/null)
    
    if echo "$resp" | jq -e '.nodeId // .data.nodeId' >/dev/null 2>&1; then
        local node_id=$(echo "$resp" | jq -r '.nodeId // .data.nodeId')
        save_node_id "$node_id"
        echo "✅ Registered with SkyNet: $node_id"
        return 0
    else
        echo "❌ Registration failed: $(echo "$resp" | jq -r '.error // .message // "Unknown"')"
        return 1
    fi
}

# Send heartbeat to SkyNet
send_heartbeat() {
    local node_id=$(load_node_id)
    [[ -z "$node_id" ]] && { register_node || return 1; }
    
    local block_hex=$(curl -s -m 10 -X POST "$RPC_URL" \
        -H 'Content-Type: application/json' \
        -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' | jq -r '.result // "0x0"')
    local block_height=$((16#${block_hex#0x}))
    
    local peers_hex=$(curl -s -m 10 -X POST "$RPC_URL" \
        -H 'Content-Type: application/json' \
        -d '{"jsonrpc":"2.0","method":"net_peerCount","params":[],"id":1}' | jq -r '.result // "0x0"')
    local peers=$((16#${peers_hex#0x}))
    
    local syncing=$(curl -s -m 10 -X POST "$RPC_URL" \
        -H 'Content-Type: application/json' \
        -d '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' | jq -r '.result != false')
    
    local payload=$(cat << PAYLOAD_EOF
{
    "nodeId":"$node_id",
    "blockHeight":$block_height,
    "peerCount":$peers,
    "syncing":$syncing,
    "timestamp":"$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
PAYLOAD_EOF
)
    
    local resp
    resp=$(curl -s -m 15 -X POST "${SKYNET_URL}/api/nodes/heartbeat" \
        -H 'Content-Type: application/json' \
        -H "X-API-Key: $API_KEY" \
        -d "$payload" 2>/dev/null)
    
    if echo "$resp" | jq -e '.ok // .success' >/dev/null 2>&1; then
        echo "$(date '+%H:%M:%S') ✅ Heartbeat: block=$block_height peers=$peers"
    else
        echo "$(date '+%H:%M:%S') ❌ Heartbeat failed"
    fi
}

# Main loop
main() {
    echo "Starting SkyNet agent for $NODE_NAME..."
    
    # Initial registration
    register_node
    
    # Heartbeat every 30 seconds
    while true; do
        send_heartbeat
        sleep 30
    done
}

case "${1:-heartbeat}" in
    register) register_node ;;
    heartbeat) send_heartbeat ;;
    *) main ;;
esac
AGENT_EOF

    # Replace placeholders
    sed -i "s/NODE_NAME_PLACEHOLDER/$node_name/g" "${output_dir}/skynet-agent-${node_name}.sh"
    sed -i "s/NETWORK_PLACEHOLDER/$network/g" "${output_dir}/skynet-agent-${node_name}.sh"
    sed -i "s/RPC_PORT_PLACEHOLDER/$rpc_port/g" "${output_dir}/skynet-agent-${node_name}.sh"
    sed -i "s|SKYNET_URL_PLACEHOLDER|$GP5_SKYNET_URL|g" "${output_dir}/skynet-agent-${node_name}.sh"
    sed -i "s/SKYNET_API_KEY_PLACEHOLDER/$GP5_SKYNET_API_KEY/g" "${output_dir}/skynet-agent-${node_name}.sh"
    sed -i "s|OUTPUT_DIR_PLACEHOLDER|$output_dir|g" "${output_dir}/skynet-agent-${node_name}.sh"
    local chain_id=$([[ "$network" == "mainnet" ]] && echo 50 || echo 51)
    sed -i "s/CHAIN_ID_PLACEHOLDER/$chain_id/g" "${output_dir}/skynet-agent-${node_name}.sh"
    
    chmod +x "${output_dir}/skynet-agent-${node_name}.sh"
    echo "${output_dir}/skynet-agent-${node_name}.sh"
}

# Generate ethstats configuration
generate_ethstats_config() {
    local node_name="$1"
    local network="${2:-mainnet}"
    local output_dir="${3:-/opt/xdc-node/ethstats}"
    
    mkdir -p "$output_dir"
    
    # Generate ethstats secret if not provided
    local ethstats_secret="${ETHSTATS_SECRET:-$(openssl rand -hex 16)}"
    
    cat > "${output_dir}/ethstats-${node_name}.conf" << EOF
# EthStats Configuration for ${node_name}
# Generated by XDC CLI GP5 Deployment Standard

ETHSTATS_NAME="${node_name}"
ETHSTATS_SECRET="${ethstats_secret}"
ETHSTATS_SERVER="${GP5_ETHSTATS_SERVER}"
ETHSTATS_CONTACT="${ETHSTATS_CONTACT:-admin@xdc.network}"
EOF

    chmod 600 "${output_dir}/ethstats-${node_name}.conf"
    echo "${output_dir}/ethstats-${node_name}.conf"
}

# Get ethstats connection string for docker
get_ethstats_string() {
    local node_name="$1"
    local secret="${2:-$(openssl rand -hex 16)}"
    echo "${node_name}:${secret}@${GP5_ETHSTATS_SERVER}"
}

# Validate GP5 deployment
validate_gp5_deployment() {
    local node_name="$1"
    local rpc_url="${2:-http://localhost:8545}"
    local max_wait_minutes="${3:-5}"
    
    echo "Validating GP5 deployment for ${node_name}..."
    echo "Waiting up to ${max_wait_minutes} minutes for visibility..."
    
    local start_time=$(date +%s)
    local end_time=$((start_time + max_wait_minutes * 60))
    
    local skynet_visible=false
    local ethstats_visible=false
    local block_syncing=false
    
    while [[ $(date +%s) -lt $end_time ]]; do
        # Check SkyNet visibility
        if [[ "$skynet_visible" == "false" ]]; then
            local skynet_check
            skynet_check=$(curl -s -m 10 "${GP5_SKYNET_URL}/api/nodes/${node_name}" \
                -H "X-API-Key: ${GP5_SKYNET_API_KEY}" 2>/dev/null | jq -r '.name // empty')
            if [[ "$skynet_check" == "$node_name" ]]; then
                echo "✅ SkyNet: Node visible"
                skynet_visible=true
            fi
        fi
        
        # Check ethstats visibility
        if [[ "$ethstats_visible" == "false" ]]; then
            local ethstats_check
            ethstats_check=$(curl -s -m 10 "https://${GP5_ETHSTATS_SERVER}/api/nodes/${node_name}" 2>/dev/null | jq -r '.name // empty')
            if [[ "$ethstats_check" == "$node_name" ]]; then
                echo "✅ EthStats: Node visible"
                ethstats_visible=true
            fi
        fi
        
        # Check block sync
        if [[ "$block_syncing" == "false" ]]; then
            local block_hex
            block_hex=$(curl -s -m 5 -X POST "$rpc_url" \
                -H 'Content-Type: application/json' \
                -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' 2>/dev/null | jq -r '.result // "0x0"')
            local block_height=$((16#${block_hex#0x}))
            if [[ $block_height -gt 0 ]]; then
                echo "✅ Block Sync: Height ${block_height}"
                block_syncing=true
            fi
        fi
        
        # Check if all validations passed
        if [[ "$skynet_visible" == "true" ]] && [[ "$ethstats_visible" == "true" ]] && [[ "$block_syncing" == "true" ]]; then
            echo ""
            echo "🎉 GP5 Deployment Validation PASSED"
            return 0
        fi
        
        echo -n "."
        sleep 10
    done
    
    echo ""
    echo "⚠️  GP5 Deployment Validation Results:"
    [[ "$skynet_visible" == "true" ]] && echo "  ✅ SkyNet visible" || echo "  ❌ SkyNet NOT visible"
    [[ "$ethstats_visible" == "true" ]] && echo "  ✅ EthStats visible" || echo "  ❌ EthStats NOT visible"
    [[ "$block_syncing" == "true" ]] && echo "  ✅ Block sync active" || echo "  ❌ Block sync NOT active"
    
    return 1
}

# Create docker-compose override for GP5 standard
generate_gp5_compose_override() {
    local node_name="$1"
    local network="${2:-mainnet}"
    local rpc_port="${3:-8545}"
    local output_file="${4:-docker-compose.gp5.yml}"
    
    local ethstats_secret=$(openssl rand -hex 16)
    local ethstats_string="${node_name}:${ethstats_secret}@${GP5_ETHSTATS_SERVER}"
    local chain_id=$([[ "$network" == "mainnet" ]] && echo 50 || echo 51)
    
    cat > "$output_file" << EOF
# GP5 Deployment Standard - Docker Compose Override
# Auto-generated for ${node_name}
version: '3.8'

services:
  xdc-node:
    environment:
      - SKYNET_URL=${GP5_SKYNET_URL}
      - SKYNET_API_KEY=${GP5_SKYNET_API_KEY}
      - ETHSTATS_SECRET=${ethstats_secret}
      - ETHSTATS_NAME=${node_name}
    command:
      - --ethstats
      - "${ethstats_string}"
      - --nodiscover
    labels:
      - "gp5.standard=true"
      - "gp5.version=${GP5_VERSION}"
      - "skynet.enabled=true"
      - "ethstats.enabled=true"

  skynet-agent:
    image: anilchinchawale/xdc-agent:latest
    container_name: skynet-agent-${node_name}
    restart: unless-stopped
    environment:
      - RPC_URL=http://xdc-node:${rpc_port}
      - SKYNET_NODE_NAME=${node_name}
      - SKYNET_API_URL=${GP5_SKYNET_URL}/api
      - SKYNET_MASTER_KEY=${GP5_SKYNET_API_KEY}
      - XDC_CONTAINER_NAME=xdc-node
      - NEXT_PUBLIC_REFRESH_INTERVAL=30
    networks:
      - xdc-net
    depends_on:
      - xdc-node
EOF

    echo "$output_file"
}
