#!/bin/bash
set -euo pipefail

# Smart Contract Verification Integration
# Issue #523: Add smart contract source code verification to XDC CLI
# Integrates with XDC Explorer verification API

readonly SCRIPT_VERSION="1.0.0"
readonly CONFIG_DIR="${XDC_CONFIG_DIR:-$HOME/.xdc-node}"
readonly LOG_FILE="${XDC_LOG_DIR:-/var/log/xdc}/contract-verify.log"

# API endpoints
XDCSCAN_API="${XDCSCAN_API:-https://api.xdcscan.io/api}"
XDCSCAN_TESTNET_API="${XDCSCAN_TESTNET_API:-https://api-testnet.xdcscan.io/api}"

# Logging
log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"; }
info() { log "INFO: $*"; }
warn() { log "WARN: $*" >&2; }
error() { log "ERROR: $*" >&2; }

# Initialize
init() {
    mkdir -p "$CONFIG_DIR" "$(dirname "$LOG_FILE")"
}

# Detect network from address prefix
detect_network() {
    local address=$1
    
    case "${address:0:3}" in
        xdc) echo "mainnet" ;;
        XDC) echo "mainnet" ;;
        *) echo "apothem" ;;
    esac
}

# Get API URL for network
get_api_url() {
    local network=$1
    
    case $network in
        mainnet) echo "$XDCSCAN_API" ;;
        apothem) echo "$XDCSCAN_TESTNET_API" ;;
        testnet) echo "$XDCSCAN_TESTNET_API" ;;
        *) echo "$XDCSCAN_API" ;;
    esac
}

# Flatten multi-file contracts
flatten_contract() {
    local source_dir=$1
    local output_file=$2
    
    info "Flattening contracts from $source_dir..."
    
    {
        echo "// SPDX-License-Identifier: MIT"
        echo "// Flattened contract generated by XDC Contract Verifier"
        echo "// Source: $source_dir"
        echo "// Generated: $(date -Iseconds)"
        echo ""
        
        # Process files in order: libraries first, then main contract
        find "$source_dir" -name "*.sol" -type f | while read -r file; do
            echo ""
            echo "// File: $(basename "$file")"
            echo "// ------------------------------------------------------------------------"
            
            # Remove SPDX lines and pragma statements (except first)
            grep -v "^// SPDX-License-Identifier:" "$file" | \
            grep -v "^pragma solidity" | \
            grep -v "^import"
        done
        
        # Add pragma at the beginning
        local pragma_version
        pragma_version=$(grep -h "pragma solidity" "$source_dir"/*.sol | head -1)
        echo "$pragma_version"
    } > "$output_file"
    
    info "Flattened contract saved to $output_file"
}

# Verify contract on XDCScan
verify_contract() {
    local address=$1
    local source_path=$2
    local compiler_version=$3
    local optimize=${4:-true}
    local optimizer_runs=${5:-200}
    local constructor_args=${6:-}
    local libraries=${7:-}
    local network=${8:-mainnet}
    
    local api_url
    api_url=$(get_api_url "$network")
    
    info "Verifying contract $address on $network..."
    
    # Read source code
    local source_code
    if [[ -d "$source_path" ]]; then
        # Multi-file contract - need to flatten
        local temp_file
        temp_file=$(mktemp)
        flatten_contract "$source_path" "$temp_file"
        source_code=$(cat "$temp_file")
        rm -f "$temp_file"
    else
        source_code=$(cat "$source_path")
    fi
    
    # Escape special characters for JSON
    source_code=$(echo "$source_code" | jq -s -R '.')
    
    # Build request
    local request_data
    request_data=$(jq -n \
        --arg address "$address" \
        --arg source "$source_code" \
        --arg compiler "$compiler_version" \
        --arg optimize "$optimize" \
        --argjson runs "$optimizer_runs" \
        --arg constructor "$constructor_args" \
        --arg libraries "$libraries" \
        '{
            module: "contract",
            action: "verifysourcecode",
            contractaddress: $address,
            sourceCode: $source,
            codeformat: "solidity-single-file",
            contractname: "",
            compilerversion: $compiler,
            optimizationUsed: $optimize,
            runs: $runs,
            constructorArguements: $constructor,
            libraryAddress: $libraries
        }')
    
    # Send verification request
    local response
    response=$(curl -sf -X POST "$api_url" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        --data "module=contract&action=verifysourcecode&contractaddress=$address&sourceCode=$source_code&compilerversion=$compiler_version&optimizationUsed=$optimize&runs=$optimizer_runs" \
        2>/dev/null || echo '{"status":"0","message":"Connection failed"}')
    
    local status
    status=$(echo "$response" | jq -r '.status // "0"')
    local message
    message=$(echo "$response" | jq -r '.message // "Unknown error"')
    local result
    result=$(echo "$response" | jq -r '.result // ""')
    
    if [[ "$status" == "1" ]]; then
        info "✓ Verification submitted successfully!"
        info "  GUID: $result"
        info "  Use 'xdc contract verify-status --address $address --guid $result' to check status"
        return 0
    else
        error "✗ Verification failed: $message"
        return 1
    fi
}

# Check verification status
check_verification_status() {
    local address=$1
    local guid=$2
    local network=${3:-mainnet}
    
    local api_url
    api_url=$(get_api_url "$network")
    
    info "Checking verification status for $address..."
    
    local response
    response=$(curl -sf "$api_url?module=contract&action=checkverifystatus&guid=$guid" \
        2>/dev/null || echo '{"status":"0","message":"Connection failed"}')
    
    local status
    status=$(echo "$response" | jq -r '.status // "0"')
    local message
    message=$(echo "$response" | jq -r '.message // "Unknown"')
    
    if [[ "$status" == "1" ]]; then
        info "✓ Contract verification complete!"
        info "  View at: https://xdcscan.io/address/$address#code"
        return 0
    else
        warn "⏳ Verification pending: $message"
        return 1
    fi
}

# List verified contracts (from local cache)
list_verified_contracts() {
    local cache_file="$CONFIG_DIR/verified-contracts.json"
    
    if [[ -f "$cache_file" ]]; then
        echo "Verified Contracts:"
        jq -r '.contracts[] | "  \(.address) - \(.name) - \(.network) - \(.verified_at)"' "$cache_file" 2>/dev/null || echo "  No verified contracts found"
    else
        echo "No verified contracts in local cache"
    fi
}

# Cache verified contract
cache_verified_contract() {
    local address=$1
    local name=$2
    local network=$3
    local cache_file="$CONFIG_DIR/verified-contracts.json"
    
    local entry
    entry=$(jq -n \
        --arg address "$address" \
        --arg name "$name" \
        --arg network "$network" \
        --arg verified_at "$(date -Iseconds)" \
        '{address: $address, name: $name, network: $network, verified_at: $verified_at}')
    
    if [[ -f "$cache_file" ]]; then
        jq --argjson entry "$entry" '.contracts += [$entry]' "$cache_file" > "$cache_file.tmp" && mv "$cache_file.tmp" "$cache_file"
    else
        echo "{\"contracts\":[$entry]}" > "$cache_file"
    fi
}

# Show usage
show_help() {
    cat <<'EOF'
XDC Smart Contract Verification v1.0.0

Usage: xdc contract <command> [options]

Commands:
  verify [options] <address>     Verify contract source code
  verify-status [options]        Check verification status
  flatten <source-dir>          Flatten multi-file contracts
  list-verified                  List locally cached verified contracts

Verify Options:
  --source <path>              Path to source file or directory (required)
  --compiler <version>         Compiler version (e.g., v0.8.19+commit.7dd6d404)
  --optimize                    Enable optimizer (default: true)
  --runs <n>                    Optimizer runs (default: 200)
  --constructor-args <args>     ABI-encoded constructor arguments
  --libraries <libs>            Library addresses (lib1:addr1,lib2:addr2)
  --network <net>              Target network (mainnet/apothem/testnet)

Status Options:
  --address <addr>             Contract address
  --guid <guid>                Verification GUID
  --network <net>              Network (mainnet/apothem/testnet)

Examples:
  # Verify single file contract
  xdc contract verify 0x123... --source ./MyContract.sol --compiler v0.8.19

  # Verify multi-file contract
  xdc contract verify 0x123... --source ./contracts/ --compiler v0.8.19

  # Check verification status
  xdc contract verify-status --address 0x123... --guid abc-123

  # Flatten contracts
  xdc contract flatten ./contracts/ --output ./flattened.sol

  # Verify on Apothem testnet
  xdc contract verify 0x123... --source ./MyContract.sol --compiler v0.8.19 --network apothem
EOF
}

# Main
main() {
    init
    
    local cmd="${1:-}"
    shift || true
    
    case "$cmd" in
        verify)
            # Parse arguments
            local address=""
            local source=""
            local compiler=""
            local optimize=true
            local runs=200
            local constructor_args=""
            local libraries=""
            local network="mainnet"
            
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    --source) source="$2"; shift 2 ;;
                    --compiler) compiler="$2"; shift 2 ;;
                    --optimize) optimize=true; shift ;;
                    --runs) runs="$2"; shift 2 ;;
                    --constructor-args) constructor_args="$2"; shift 2 ;;
                    --libraries) libraries="$2"; shift 2 ;;
                    --network) network="$2"; shift 2 ;;
                    --help|-h) show_help; exit 0 ;;
                    --*) warn "Unknown option: $1"; shift ;;
                    *)
                        if [[ -z "$address" && "$1" == xdc* || "$1" == 0x* ]]; then
                            address="$1"
                        fi
                        shift
                        ;;
                esac
            done
            
            # Validate required arguments
            if [[ -z "$address" ]]; then
                error "Contract address is required"
                show_help
                exit 1
            fi
            
            if [[ -z "$source" ]]; then
                error "Source path is required (--source)"
                show_help
                exit 1
            fi
            
            if [[ -z "$compiler" ]]; then
                error "Compiler version is required (--compiler)"
                show_help
                exit 1
            fi
            
            if [[ ! -e "$source" ]]; then
                error "Source path does not exist: $source"
                exit 1
            fi
            
            verify_contract "$address" "$source" "$compiler" "$optimize" "$runs" "$constructor_args" "$libraries" "$network"
            ;;
            
        verify-status)
            local address=""
            local guid=""
            local network="mainnet"
            
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    --address) address="$2"; shift 2 ;;
                    --guid) guid="$2"; shift 2 ;;
                    --network) network="$2"; shift 2 ;;
                    --help|-h) show_help; exit 0 ;;
                    *) shift ;;
                esac
            done
            
            if [[ -z "$address" ]]; then
                error "Address is required (--address)"
                exit 1
            fi
            
            if [[ -z "$guid" ]]; then
                error "GUID is required (--guid)"
                exit 1
            fi
            
            check_verification_status "$address" "$guid" "$network"
            ;;
            
        flatten)
            local source_dir="${1:-}"
            local output="${2:-./flattened.sol}"
            
            if [[ -z "$source_dir" ]]; then
                error "Source directory is required"
                show_help
                exit 1
            fi
            
            flatten_contract "$source_dir" "$output"
            ;;
            
        list-verified)
            list_verified_contracts
            ;;
            
        --help|-h)
            show_help
            ;;
            
        *)
            error "Unknown command: $cmd"
            show_help
            exit 1
            ;;
    esac
}

main "$@"
