#!/bin/bash
#===============================================================================
# XDC Node Setup - Monitoring Integration (#86)
# Auto-configures SkyOne agent for each running XDC client container.
# Generates per-client skynet.conf with correct RPC port, client type,
# node name. Restarts skyone containers after config change.
#===============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common-lib.sh"

# SkyOne config directory
SKYONE_CONF_DIR="${SKYONE_CONF_DIR:-/opt/xdc-node/skyone}"
SKYONE_IMAGE="${SKYONE_IMAGE:-skynet.xdcindia.com/skyone:latest}"

# Client definitions: name|container_pattern|rpc_port|client_type
declare -A CLIENT_RPC_PORTS=(
    ["geth"]="7070"
    ["erigon"]="7071"
    ["nethermind"]="7072"
    ["reth"]="8588"
)

declare -A CLIENT_TYPES=(
    ["geth"]="geth-xdc"
    ["erigon"]="erigon-xdc"
    ["nethermind"]="nethermind-xdc"
    ["reth"]="reth-xdc"
)

declare -A CONTAINER_PATTERNS=(
    ["geth"]="xdc-geth\|geth-xdc\|xdc_geth"
    ["erigon"]="xdc-erigon\|erigon-xdc\|xdc_erigon"
    ["nethermind"]="xdc-nethermind\|nethermind-xdc\|xdc_nethermind"
    ["reth"]="xdc-reth\|reth-xdc\|xdc_reth"
)

#-------------------------------------------------------------------------------
usage() {
    cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Auto-configures SkyOne monitoring agent for each running XDC client container.

Options:
  -d DIR     SkyOne config directory (default: ${SKYONE_CONF_DIR})
  -n NAME    Node name prefix (default: hostname)
  -r         Dry-run: show what would be configured but don't apply
  -h         Show this help

Examples:
  $(basename "$0")
  $(basename "$0") -d /etc/skyone -n xdc-prod-01
  $(basename "$0") -r
EOF
}

#-------------------------------------------------------------------------------
detect_running_clients() {
    local running_clients=()
    
    if ! command -v docker &>/dev/null; then
        warn "Docker not found — cannot detect running containers"
        return
    fi
    
    for client in geth erigon nethermind reth; do
        local pattern="${CONTAINER_PATTERNS[$client]}"
        if docker ps --format '{{.Names}}' 2>/dev/null | grep -qE "$pattern"; then
            running_clients+=("$client")
            log "Detected running client: $client"
        fi
    done
    
    echo "${running_clients[@]:-}"
}

#-------------------------------------------------------------------------------
generate_skynet_conf() {
    local client="$1"
    local node_name="$2"
    local rpc_port="${CLIENT_RPC_PORTS[$client]}"
    local client_type="${CLIENT_TYPES[$client]}"
    local conf_file="${SKYONE_CONF_DIR}/${client}/skynet.conf"
    
    info "Generating skynet.conf for ${client} (port=${rpc_port}, type=${client_type})"
    
    mkdir -p "${SKYONE_CONF_DIR}/${client}"
    
    cat > "${conf_file}" <<EOF
# SkyOne Agent Configuration — generated by monitoring-setup.sh
# Client: ${client_type}
# Node:   ${node_name}-${client}

[agent]
node_name       = "${node_name}-${client}"
client_type     = "${client_type}"
network         = "xdc-mainnet"

[rpc]
endpoint        = "http://127.0.0.1:${rpc_port}"
timeout_ms      = 5000
retry_attempts  = 3

[metrics]
poll_interval   = 15
collect_peers   = true
collect_sync    = true
collect_blocks  = true

[reporting]
server_url      = "https://skynet.xdcindia.com"
push_interval   = 30
auth_token      = "\${SKYONE_AUTH_TOKEN}"

[alerts]
sync_lag_blocks = 10
min_peers       = 3
EOF
    
    log "Written: ${conf_file}"
}

#-------------------------------------------------------------------------------
restart_skyone_container() {
    local client="$1"
    local container_name="skyone-${client}"
    
    if docker ps -a --format '{{.Names}}' 2>/dev/null | grep -q "^${container_name}$"; then
        info "Restarting SkyOne container: ${container_name}"
        docker restart "${container_name}" && log "Restarted ${container_name}" || warn "Failed to restart ${container_name}"
    else
        info "SkyOne container '${container_name}' not found — skipping restart"
        info "To start: docker run -d --name ${container_name} \\"
        info "  -v ${SKYONE_CONF_DIR}/${client}/skynet.conf:/etc/skyone/skynet.conf:ro \\"
        info "  --network host ${SKYONE_IMAGE}"
    fi
}

#-------------------------------------------------------------------------------
main() {
    local dry_run=false
    local node_name
    node_name="$(hostname -s)"
    
    while getopts "d:n:rh" opt; do
        case "$opt" in
            d) SKYONE_CONF_DIR="$OPTARG" ;;
            n) node_name="$OPTARG" ;;
            r) dry_run=true ;;
            h) usage; exit 0 ;;
            *) usage; exit 1 ;;
        esac
    done
    
    info "XDC Monitoring Integration Setup"
    info "SkyOne config dir: ${SKYONE_CONF_DIR}"
    info "Node name prefix:  ${node_name}"
    
    if $dry_run; then
        warn "DRY RUN — no changes will be made"
    fi
    
    # Detect running clients
    local clients_str
    clients_str="$(detect_running_clients)" || true
    
    if [[ -z "${clients_str}" ]]; then
        warn "No running XDC client containers detected"
        info "Configuring all known clients anyway..."
        clients_str="geth erigon nethermind reth"
    fi
    
    read -ra clients <<< "$clients_str"
    local configured=0
    
    for client in "${clients[@]}"; do
        if [[ -z "$client" ]]; then continue; fi
        
        if ! $dry_run; then
            generate_skynet_conf "$client" "$node_name"
            restart_skyone_container "$client"
        else
            local rpc_port="${CLIENT_RPC_PORTS[$client]:-unknown}"
            local client_type="${CLIENT_TYPES[$client]:-unknown}"
            echo "  [DRY RUN] Would configure: ${client} → port=${rpc_port}, type=${client_type}, conf=${SKYONE_CONF_DIR}/${client}/skynet.conf"
        fi
        ((configured++))
    done
    
    if ! $dry_run; then
        log "Monitoring setup complete: ${configured} client(s) configured"
    else
        log "Dry run complete: ${configured} client(s) would be configured"
    fi
}

main "$@"
