#!/usr/bin/env bash
#==============================================================================
# RPC Rate Limiter (Issue #496)
# Nginx config generator for RPC rate limiting
#==============================================================================
set -euo pipefail

RATE="${1:-100}"  # requests per minute
BURST="${2:-50}"

cat << NGINX
# XDC RPC Rate Limiting (Issue #496)
# Generated by rpc-rate-limiter.sh

limit_req_zone \$binary_remote_addr zone=rpc_limit:10m rate=${RATE}r/m;
limit_req_zone \$http_x_api_key zone=api_key_limit:10m rate=1000r/m;

server {
    listen 8545;
    
    location / {
        # Rate limit by IP (unauthenticated)
        limit_req zone=rpc_limit burst=$BURST nodelay;
        limit_req_status 429;
        
        # Higher limit for API key holders
        limit_req zone=api_key_limit burst=200 nodelay;
        
        proxy_pass http://127.0.0.1:18545;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        
        # CORS
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "POST, GET, OPTIONS";
    }
}
NGINX
