#!/usr/bin/env bash
set -euo pipefail

#==============================================================================
# Security Hardening Script for XDC Nodes
# Implements ALL industry-grade security standards from XDC-NODE-STANDARDS.md
#==============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPORT_DIR="/opt/xdc-node/reports"
REPORT_FILE="$REPORT_DIR/security-audit-$(date +%Y%m%d-%H%M%S).txt"
SCORE_FILE="$REPORT_DIR/security-score.json"
LOG_FILE="/var/log/xdc-security-harden.log"

# Ensure report directory exists
mkdir -p "$REPORT_DIR"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Score tracking - 11 checks total, 100 points
TOTAL_SCORE=0
MAX_SCORE=100

# Individual check scores (for JSON output)
declare -A CHECK_SCORES
declare -A CHECK_MAX
declare -A CHECK_STATUS

# Initialize all checks
init_checks() {
    CHECK_MAX["ssh_key_only"]=10
    CHECK_MAX["ssh_nonstandard_port"]=5
    CHECK_MAX["firewall_active"]=10
    CHECK_MAX["fail2ban_running"]=5
    CHECK_MAX["unattended_upgrades"]=5
    CHECK_MAX["os_patches_current"]=10
    CHECK_MAX["client_version_current"]=15
    CHECK_MAX["monitoring_active"]=10
    CHECK_MAX["backup_configured"]=10
    CHECK_MAX["audit_logging"]=10
    CHECK_MAX["disk_encryption"]=10
}

log() {
    echo -e "${GREEN}[$(date '+%Y-%m-%d %H:%M:%S')] $1${NC}"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$REPORT_FILE" 2>/dev/null || true
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE" 2>/dev/null || true
}

warn() {
    echo -e "${YELLOW}[$(date '+%Y-%m-%d %H:%M:%S')] WARNING: $1${NC}"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] WARNING: $1" >> "$REPORT_FILE" 2>/dev/null || true
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] WARNING: $1" >> "$LOG_FILE" 2>/dev/null || true
}

error() {
    echo -e "${RED}[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $1${NC}"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $1" >> "$REPORT_FILE" 2>/dev/null || true
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $1" >> "$LOG_FILE" 2>/dev/null || true
}

add_score() {
    local check_name=$1
    local points=$2
    local status=$3
    local description=$4
    local max=${CHECK_MAX[$check_name]}
    
    TOTAL_SCORE=$((TOTAL_SCORE + points))
    CHECK_SCORES[$check_name]=$points
    CHECK_STATUS[$check_name]="$status"
    
    local status_icon="✓"
    [[ "$status" == "fail" ]] && status_icon="✗"
    [[ "$status" == "warning" ]] && status_icon="⚠"
    
    log "$status_icon $description - $points/$max points"
}

#==============================================================================
# Pre-flight Checks
#==============================================================================
check_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script must be run as root"
        exit 1
    fi
}

#==============================================================================
# SSH Hardening (Section 1.1)
#==============================================================================
ssh_hardening() {
    log "=== SSH Hardening ==="
    
    local sshd_config="/etc/ssh/sshd_config"
    local backup_file="/etc/ssh/sshd_config.backup.$(date +%Y%m%d)"
    
    # Backup existing config
    cp "$sshd_config" "$backup_file"
    log "Backup created: $backup_file"
    
    # SSH hardening configuration - Key-only, non-standard port 12141, MaxAuthTries 3, AllowUsers
    cat > "$sshd_config" << 'EOF'
# XDC Node Hardened SSH Configuration
# Generated by security-harden.sh - Implements Section 1.1 of XDC Standards

Port 12141
AddressFamily any
ListenAddress 0.0.0.0
ListenAddress ::

HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

# Authentication - Key-only
PermitRootLogin prohibit-password
PasswordAuthentication no
PubkeyAuthentication yes
AuthenticationMethods publickey
ChallengeResponseAuthentication no
UsePAM yes

# Connection limits
MaxAuthTries 3
MaxSessions 2
ClientAliveInterval 300
ClientAliveCountMax 2
LoginGraceTime 60

# User restrictions - explicit allowlist
AllowUsers root
DenyUsers nobody

# Disable X11 and unnecessary features
X11Forwarding no
PrintMotd no
PrintLastLog yes
TCPKeepAlive no

AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server

# Strong crypto settings
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
EOF
    
    # Test SSH config before applying
    if sshd -t; then
        systemctl restart sshd
        log "✓ SSH configuration updated (Port: 12141, Key-only auth, MaxAuthTries: 3, AllowUsers: root)"
        add_score "ssh_key_only" 10 "pass" "SSH key-only authentication"
        add_score "ssh_nonstandard_port" 5 "pass" "SSH non-standard port (12141)"
    else
        warn "SSH config test failed, restoring backup"
        cp "$backup_file" "$sshd_config"
        systemctl restart sshd
        add_score "ssh_key_only" 0 "fail" "SSH key-only authentication (failed)"
        add_score "ssh_nonstandard_port" 0 "fail" "SSH non-standard port (failed)"
    fi
}

#==============================================================================
# Firewall Configuration (UFW) - Section 1.2
#==============================================================================
setup_firewall() {
    log "=== Firewall (UFW) Configuration ==="
    
    # Install UFW if not present
    if ! command -v ufw &> /dev/null; then
        apt-get update -qq
        apt-get install -y -qq ufw
    fi
    
    # Reset to defaults
    ufw --force reset
    
    # Default policies: deny incoming, allow outgoing
    ufw default deny incoming
    ufw default allow outgoing
    
    # SSH (custom port 12141) - never expose 22
    ufw allow 12141/tcp comment "SSH (hardened - non-standard port)"
    
    # XDC P2P
    ufw allow 30303/tcp comment "XDC P2P"
    ufw allow 30303/udp comment "XDC P2P Discovery"
    
    # Monitoring (localhost only) - NEVER expose RPC publicly
    ufw allow from 127.0.0.1 to any port 9090 comment "Prometheus (local only)"
    ufw allow from 127.0.0.1 to any port 3000 comment "Grafana (local only)"
    
    # Rate limiting for SSH
    ufw limit 12141/tcp comment "SSH rate limit"
    
    # Enable firewall
    echo "y" | ufw enable
    
    if ufw status | grep -q "Status: active"; then
        log "✓ UFW firewall active (deny incoming, allow 12141/tcp, 30303/tcp+udp, NO public RPC)"
        add_score "firewall_active" 10 "pass" "UFW firewall active"
    else
        warn "UFW activation may have failed"
        add_score "firewall_active" 0 "fail" "UFW firewall (failed)"
    fi
}

#==============================================================================
# Fail2ban Configuration - Section 1.3
#==============================================================================
setup_fail2ban() {
    log "=== Fail2ban Configuration ==="
    
    # Install fail2ban if not present
    if ! command -v fail2ban-server &> /dev/null; then
        apt-get update -qq
        apt-get install -y -qq fail2ban
    fi
    
    # Create local jail configuration with port 12141, maxretry 3, bantime 3600
    cat > /etc/fail2ban/jail.local << 'EOF'
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 3
backend = auto
usedns = no
logencoding = UTF-8
enabled = false
mode = normal
filter = %(__name__)s[mode=%(mode)s]

[sshd]
enabled = true
port = 12141
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 3600
findtime = 600
backend = systemd
EOF
    
    systemctl restart fail2ban
    systemctl enable fail2ban
    
    if systemctl is-active --quiet fail2ban; then
        log "✓ Fail2ban running (port: 12141, maxretry: 3, bantime: 3600)"
        add_score "fail2ban_running" 5 "pass" "Fail2ban running"
    else
        warn "Fail2ban service failed to start"
        add_score "fail2ban_running" 0 "fail" "Fail2ban (failed)"
    fi
}

#==============================================================================
# Auditd Setup - Section 2.2
#==============================================================================
setup_auditd() {
    log "=== Auditd Configuration ==="
    
    # Install auditd if not present
    if ! command -v auditd &> /dev/null; then
        apt-get update -qq
        apt-get install -y -qq auditd audispd-plugins
    fi
    
    # Configure audit rules for admin commands, chaindata access, auth log
    cat > /etc/audit/rules.d/xdc-node.rules << 'EOF'
# XDC Node Audit Rules - Section 2.2
-D
-b 8192

# Monitor sudoers file
-w /etc/sudoers -p wa -k sudoers_changes
-w /etc/sudoers.d/ -p wa -k sudoers_changes

# Monitor SSH configuration
-w /etc/ssh/sshd_config -p wa -k ssh_config_changes

# Monitor XDC node data access (chaindata)
-w /root/xdcchain -p rwxa -k chaindata_access
-w /opt/xdc-node -p rwxa -k xdc_config_access

# Monitor auth log
-w /var/log/auth.log -p wa -k auth_log

# Monitor Docker socket
-w /var/run/docker.sock -p wa -k docker_access

# Admin commands
-a always,exit -F arch=b64 -S execve -F uid=0 -k admin_commands

# Privilege escalation
-a always,exit -F arch=b64 -S setuid -S setgid -S setreuid -S setregid -k privilege_escalation

-e 2
EOF
    
    service auditd restart 2>/dev/null || auditctl -R /etc/audit/rules.d/xdc-node.rules 2>/dev/null || true
    systemctl enable auditd 2>/dev/null || true
    
    if systemctl is-active --quiet auditd || pgrep -x auditd > /dev/null; then
        log "✓ Auditd running (monitoring admin commands, chaindata access, auth log)"
        add_score "audit_logging" 10 "pass" "Audit logging active"
    else
        warn "Auditd may not be running"
        add_score "audit_logging" 5 "warning" "Audit logging (may require reboot)"
    fi
}

#==============================================================================
# Sysctl Hardening - Network + Kernel params
#==============================================================================
sysctl_hardening() {
    log "=== Sysctl Hardening ==="
    
    cat > /etc/sysctl.d/99-xdc-security.conf << 'EOF'
# XDC Node Kernel Hardening
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.conf.all.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.all.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
vm.swappiness = 10
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
fs.file-max = 2097152
kernel.panic = 10
EOF
    
    sysctl --system 2>/dev/null || true
    log "✓ Sysctl hardening applied (network + kernel params)"
}

#==============================================================================
# Unattended Upgrades
#==============================================================================
setup_unattended_upgrades() {
    log "=== Unattended Upgrades ==="
    
    if ! dpkg -l | grep -q unattended-upgrades; then
        apt-get update -qq
        apt-get install -y -qq unattended-upgrades apt-listchanges
    fi
    
    cat > /etc/apt/apt.conf.d/50unattended-upgrades << 'EOF'
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};
Unattended-Upgrade::Package-Blacklist { "docker"; "docker-ce"; };
Unattended-Upgrade::AutoFixInterruptedDpkg "true";
Unattended-Upgrade::MinimalSteps "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "false";
EOF
    
    cat > /etc/apt/apt.conf.d/20auto-upgrades << 'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
EOF
    
    systemctl restart unattended-upgrades 2>/dev/null || true
    systemctl enable unattended-upgrades 2>/dev/null || true
    
    if dpkg -l | grep -q "unattended-upgrades"; then
        log "✓ Unattended upgrades configured"
        add_score "unattended_upgrades" 5 "pass" "Unattended upgrades enabled"
    else
        add_score "unattended_upgrades" 0 "fail" "Unattended upgrades (failed)"
    fi
}

#==============================================================================
# Check OS Patches
#==============================================================================
check_os_patches() {
    log "=== OS Patch Status ==="
    
    apt-get update -qq 2>/dev/null || true
    
    local upgradable_count
    upgradable_count=$(apt list --upgradable 2>/dev/null | grep -c upgradable || echo "0")
    
    if [[ "$upgradable_count" -eq 0 ]]; then
        log "✓ All OS packages are up to date"
        add_score "os_patches_current" 10 "pass" "OS patches current"
    else
        warn "$upgradable_count packages can be upgraded"
        DEBIAN_FRONTEND=noninteractive apt-get upgrade -y -qq 2>/dev/null || true
        add_score "os_patches_current" 5 "warning" "OS patches ($upgradable_count pending)"
    fi
}

#==============================================================================
# Check Client Version
#==============================================================================
check_client_version() {
    log "=== Client Version Check ==="
    local versions_file="/opt/xdc-node/configs/versions.json"
    
    if [[ -f "$versions_file" ]]; then
        log "✓ Client version tracking enabled"
        add_score "client_version_current" 15 "pass" "Client version tracking enabled"
    else
        warn "versions.json not found"
        add_score "client_version_current" 0 "fail" "Client version tracking (not configured)"
    fi
}

#==============================================================================
# Check Monitoring Status
#==============================================================================
check_monitoring() {
    log "=== Monitoring Status ==="
    
    if docker ps 2>/dev/null | grep -qE "prometheus|grafana"; then
        log "✓ Monitoring stack active (Prometheus + Grafana)"
        add_score "monitoring_active" 10 "pass" "Monitoring active"
    else
        warn "Monitoring stack not detected"
        add_score "monitoring_active" 0 "fail" "Monitoring (not active)"
    fi
}

#==============================================================================
# Check Backup Configuration
#==============================================================================
check_backup() {
    log "=== Backup Configuration ==="
    
    if [[ -f "/etc/cron.d/xdc-node" ]] && grep -q "backup.sh" /etc/cron.d/xdc-node 2>/dev/null; then
        log "✓ Backup configured"
        add_score "backup_configured" 10 "pass" "Backup configured"
    else
        warn "Backup not fully configured"
        add_score "backup_configured" 0 "fail" "Backup (not configured)"
    fi
}

#==============================================================================
# LUKS Disk Encryption Detection
#==============================================================================
check_disk_encryption() {
    log "=== Disk Encryption (LUKS) ==="
    
    if lsblk -f 2>/dev/null | grep -q "crypto_LUKS"; then
        log "✓ LUKS encryption detected"
        add_score "disk_encryption" 10 "pass" "Disk encryption (LUKS)"
    else
        log "⚠️  LUKS encryption not detected on data volumes."
        log ""
        log "For production deployments, consider encrypting chain data:"
        log "  1. apt-get install cryptsetup"
        log "  2. cryptsetup luksFormat /dev/sdX"
        log "  3. cryptsetup open /dev/sdX xdcchain-encrypted"
        log "  4. mkfs.ext4 /dev/mapper/xdcchain-encrypted"
        log ""
        add_score "disk_encryption" 0 "warning" "Disk encryption (not detected)"
    fi
}

#==============================================================================
# Disable Unused Services
#==============================================================================
disable_unused_services() {
    log "=== Disabling Unused Services ==="
    local services=("cups" "avahi-daemon" "bluetooth")
    for service in "${services[@]}"; do
        systemctl stop "$service" 2>/dev/null || true
        systemctl disable "$service" 2>/dev/null || true
    done
    log "✓ Unused services disabled"
}

#==============================================================================
# Secure File Permissions
#==============================================================================
secure_permissions() {
    log "=== Securing File Permissions ==="
    chmod 700 /root/.ssh 2>/dev/null || true
    chmod 600 /root/.ssh/authorized_keys 2>/dev/null || true
    chmod 750 /root/xdcchain 2>/dev/null || true
    chmod 700 /root/xdcchain/keystore 2>/dev/null || true
    chmod 750 /opt/xdc-node 2>/dev/null || true
    chmod 600 /opt/xdc-node/configs/*.env 2>/dev/null || true
    log "✓ File permissions secured"
}

#==============================================================================
# Generate Security Score Report (JSON + Human Readable)
#==============================================================================
generate_report() {
    local percentage=$((TOTAL_SCORE * 100 / MAX_SCORE))
    local rating rating_icon
    
    if [[ $percentage -ge 90 ]]; then rating="Excellent"; rating_icon="🟢"
    elif [[ $percentage -ge 70 ]]; then rating="Good"; rating_icon="🟡"
    elif [[ $percentage -ge 50 ]]; then rating="Fair"; rating_icon="🟠"
    else rating="Poor"; rating_icon="🔴"; fi
    
    # Generate JSON report
    local json_checks=""
    for key in "${!CHECK_SCORES[@]}"; do
        [[ -n "$json_checks" ]] && json_checks+=","
        json_checks+="\n    \"$key\": {\"score\": ${CHECK_SCORES[$key]}, \"max\": ${CHECK_MAX[$key]}, \"status\": \"${CHECK_STATUS[$key]}\"}"
    done
    
    cat > "$SCORE_FILE" << EOF
{
  "timestamp": "$(date -Iseconds)",
  "hostname": "$(hostname)",
  "ip": "$(hostname -I | awk '{print $1}')",
  "totalScore": $TOTAL_SCORE,
  "maxScore": $MAX_SCORE,
  "percentage": $percentage,
  "rating": "$rating",
  "checks": {$json_checks
  }
}
EOF
    
    # Human-readable report
    cat >> "$REPORT_FILE" << EOF

==================================
Security Audit Report
==================================
Generated: $(date)
Server: $(hostname)
IP: $(hostname -I | awk '{print $1}')
TOTAL SCORE: $TOTAL_SCORE/$MAX_SCORE ($percentage%)
Rating: $rating_icon $rating
==================================
EOF
    
    log ""
    log "=================================="
    log "Security Hardening Complete!"
    log "=================================="
    log "Score: $TOTAL_SCORE/$MAX_SCORE ($percentage%)"
    log "Rating: $rating_icon $rating"
    log "Report: $REPORT_FILE"
    log "JSON: $SCORE_FILE"
    log ""
    
    if [[ $percentage -ge 90 ]]; then echo -e "${GREEN}🟢 Production Ready${NC}"
    elif [[ $percentage -ge 70 ]]; then echo -e "${YELLOW}🟡 Minor improvements needed${NC}"
    elif [[ $percentage -ge 50 ]]; then echo -e "${YELLOW}🟠 Significant gaps, prioritize fixes${NC}"
    else echo -e "${RED}🔴 Not suitable for production${NC}"; fi
    
    log ""
    log "IMPORTANT: Your SSH port is now 12141"
    log "Update your connection: ssh -p 12141 root@<your-server-ip>"
}

#==============================================================================
# Main
#==============================================================================
main() {
    log "Starting XDC Node Security Hardening..."
    
    check_root
    init_checks
    
    ssh_hardening
    setup_firewall
    setup_fail2ban
    setup_auditd
    sysctl_hardening
    setup_unattended_upgrades
    check_os_patches
    check_client_version
    check_monitoring
    check_backup
    check_disk_encryption
    disable_unused_services
    secure_permissions
    
    generate_report
    
    [[ $TOTAL_SCORE -ge 70 ]] && exit 0 || exit 1
}

main "$@"
