#!/usr/bin/env bash
set -euo pipefail

#==============================================================================
# Security Hardening Script for XDC Nodes
# Implements industry-grade security standards
#==============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPORT_FILE="/opt/xdc-node/reports/security-audit-$(date +%Y%m%d-%H%M%S).txt"
SCORE_FILE="/opt/xdc-node/reports/security-score.json"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Score tracking
TOTAL_SCORE=0
MAX_SCORE=0

log() {
    echo -e "${GREEN}[$(date '+%Y-%m-%d %H:%M:%S')] $1${NC}"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$REPORT_FILE" 2>/dev/null || true
}

warn() {
    echo -e "${YELLOW}[$(date '+%Y-%m-%d %H:%M:%S')] WARNING: $1${NC}"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] WARNING: $1" >> "$REPORT_FILE" 2>/dev/null || true
}

error() {
    echo -e "${RED}[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $1${NC}"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $1" >> "$REPORT_FILE" 2>/dev/null || true
}

add_score() {
    local points=$1
    local max=$2
    local description=$3
    TOTAL_SCORE=$((TOTAL_SCORE + points))
    MAX_SCORE=$((MAX_SCORE + max))
    log "Score: $description - $points/$max points"
}

#==============================================================================
# Pre-flight Checks
#==============================================================================
check_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script must be run as root"
        exit 1
    fi
}

#==============================================================================
# SSH Hardening
#==============================================================================
ssh_hardening() {
    log "Configuring SSH hardening..."
    
    local sshd_config="/etc/ssh/sshd_config"
    local backup_file="/etc/ssh/sshd_config.backup.$(date +%Y%m%d)"
    
    # Backup existing config
    cp "$sshd_config" "$backup_file"
    log "Backup created: $backup_file"
    
    # SSH hardening configuration
    cat > "$sshd_config" << 'EOF'
# XDC Node Hardened SSH Configuration
# Generated by security-harden.sh

Port 12141
AddressFamily any
ListenAddress 0.0.0.0
ListenAddress ::

HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

PermitRootLogin prohibit-password
PasswordAuthentication no
PubkeyAuthentication yes
AuthenticationMethods publickey
ChallengeResponseAuthentication no
UsePAM yes

MaxAuthTries 3
MaxSessions 2
ClientAliveInterval 300
ClientAliveCountMax 2
LoginGraceTime 60

X11Forwarding no
PrintMotd no
PrintLastLog yes

AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server

# Security headers
AllowUsers root
DenyUsers nobody

# Crypto settings
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
EOF
    
    # Test SSH config before applying
    if sshd -t; then
        systemctl restart sshd
        log "SSH configuration updated (Port: 12141, Key-only auth)"
        add_score 15 15 "SSH Hardening (key-only, non-standard port, crypto settings)"
    else
        warn "SSH config test failed, restoring backup"
        cp "$backup_file" "$sshd_config"
        systemctl restart sshd
        add_score 0 15 "SSH Hardening (failed)"
    fi
}

#==============================================================================
# Firewall Configuration
#==============================================================================
setup_firewall() {
    log "Setting up UFW firewall..."
    
    # Install UFW if not present
    if ! command -v ufw &> /dev/null; then
        apt-get update -qq
        apt-get install -y -qq ufw
    fi
    
    # Reset to defaults
    ufw --force reset
    
    # Default policies
    ufw default deny incoming
    ufw default allow outgoing
    
    # SSH (custom port)
    ufw allow 12141/tcp comment "SSH (hardened)"
    
    # XDC P2P
    ufw allow 30303/tcp comment "XDC P2P"
    ufw allow 30303/udp comment "XDC P2P Discovery"
    
    # Monitoring (localhost only)
    ufw allow from 127.0.0.1 to any port 9090 comment "Prometheus (local)"
    ufw allow from 127.0.0.1 to any port 3000 comment "Grafana (local)"
    
    # Rate limiting for SSH
    ufw limit 12141/tcp comment "SSH rate limit"
    
    # Enable firewall
    echo "y" | ufw enable
    
    log "Firewall configured and enabled"
    add_score 10 10 "UFW Firewall"
}

#==============================================================================
# Fail2ban Configuration
#==============================================================================
setup_fail2ban() {
    log "Setting up fail2ban..."
    
    # Install fail2ban if not present
    if ! command -v fail2ban-server &> /dev/null; then
        apt-get update -qq
        apt-get install -y -qq fail2ban
    fi
    
    # Create local jail configuration
    cat > /etc/fail2ban/jail.local << 'EOF'
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 3
backend = auto
usedns = no
logencoding = UTF-8
enabled = false
mode = normal
filter = %(__name__)s[mode=%(mode)s]

[sshd]
enabled = true
port = 12141
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 3600
findtime = 600
backend = systemd

[dropbear]
enabled = false
port = ssh
filter = dropbear
logpath = /var/log/auth.log
maxretry = 3

[selinux-ssh]
enabled = false
port = ssh
filter = selinux-ssh
logpath = /var/log/audit/audit.log
maxretry = 3

[apache-auth]
enabled = false
port = http,https
filter = apache-auth
logpath = /var/log/apache2/*error.log
maxretry = 3

[apache-badbots]
enabled = false
port = http,https
filter = apache-badbots
logpath = /var/log/apache2/*error.log
maxretry = 3

[nginx-http-auth]
enabled = false
port = http,https
filter = nginx-http-auth
logpath = /var/log/nginx/error.log
maxretry = 3
EOF
    
    # Create custom filter for XDC-related attacks
    cat > /etc/fail2ban/filter.d/xdc-node.conf << 'EOF'
[Definition]
failregex = ^.*Failed password for .* from <HOST>.*$
            ^.*Invalid user .* from <HOST>.*$
            ^.*Connection closed by authenticating user .* <HOST>.*$
            ^.*error: PAM: authentication error for .* from <HOST>.*$
ignoreregex = 
EOF
    
    systemctl restart fail2ban
    systemctl enable fail2ban
    
    log "Fail2ban configured and started"
    add_score 5 5 "Fail2ban"
}

#==============================================================================
# Auditd Setup
#==============================================================================
setup_auditd() {
    log "Setting up auditd..."
    
    # Install auditd if not present
    if ! command -v auditd &> /dev/null; then
        apt-get update -qq
        apt-get install -y -qq auditd audispd-plugins
    fi
    
    # Configure audit rules
    cat > /etc/audit/rules.d/xdc-node.rules << 'EOF'
# XDC Node Audit Rules

# Monitor sudoers file
-w /etc/sudoers -p wa -k sudoers_changes
-w /etc/sudoers.d/ -p wa -k sudoers_changes

# Monitor SSH configuration
-w /etc/ssh/sshd_config -p wa -k ssh_config_changes

# Monitor XDC node data access
-w /root/xdcchain -p rwxa -k xdc_data_access
-w /opt/xdc-node -p rwxa -k xdc_config_access

# Monitor Docker socket
-w /var/run/docker.sock -p wa -k docker_access

# Monitor system binaries
-w /usr/bin/docker -p x -k docker_binary
-w /usr/bin/docker-compose -p x -k docker_compose_binary

# Monitor login/logout
-w /var/log/wtmp -p wa -k logins
-w /var/log/btmp -p wa -k failed_logins
-w /var/log/lastlog -p wa -k lastlog

# Monitor user/group modifications
-w /etc/passwd -p wa -k user_changes
-w /etc/group -p wa -k group_changes
-w /etc/shadow -p wa -k shadow_changes

# Monitor privilege escalation
-a always,exit -F arch=b64 -S setuid -S setgid -S setreuid -S setregid -k privilege_escalation
-a always,exit -F arch=b64 -S execve -F uid=0 -k admin_commands

# Monitor network configuration changes
-a always,exit -F arch=b64 -S socket -k network_socket
-w /etc/network/ -p wa -k network_changes
-w /etc/netplan/ -p wa -k network_changes
EOF
    
    # Restart auditd to load new rules
    service auditd restart || auditctl -R /etc/audit/rules.d/xdc-node.rules
    
    systemctl enable auditd 2>/dev/null || true
    
    log "Auditd configured"
    add_score 10 10 "Audit Logging"
}

#==============================================================================
# Sysctl Hardening
#==============================================================================
sysctl_hardening() {
    log "Applying sysctl hardening..."
    
    cat > /etc/sysctl.d/99-xdc-security.conf << 'EOF'
# XDC Node Kernel Hardening

# IP Spoofing protection
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Ignore ICMP broadcast requests
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Disable source packet routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# Ignore send redirects
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Block SYN attacks
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 5

# Log Martians
net.ipv4.conf.all.log_martians = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Ignore ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# Ignore Directed pings
net.ipv4.icmp_echo_ignore_all = 0

# Disable IPv6 if not needed
# net.ipv6.conf.all.disable_ipv6 = 1
# net.ipv6.conf.default.disable_ipv6 = 1

# Memory optimization
vm.swappiness = 10
vm.dirty_ratio = 15
vm.dirty_background_ratio = 5

# Network buffers
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
net.core.netdev_max_backlog = 5000

# Connection tracking
net.netfilter.nf_conntrack_max = 2000000
net.netfilter.nf_conntrack_tcp_timeout_established = 86400

# File handles
fs.file-max = 2097152
fs.nr_open = 2097152
EOF
    
    # Apply sysctl settings
    sysctl --system
    
    log "Sysctl hardening applied"
    add_score 10 10 "Sysctl Hardening"
}

#==============================================================================
# Unattended Upgrades
#==============================================================================
setup_unattended_upgrades() {
    log "Setting up unattended upgrades..."
    
    # Install unattended-upgrades if not present
    if ! dpkg -l | grep -q unattended-upgrades; then
        apt-get update -qq
        apt-get install -y -qq unattended-upgrades apt-listchanges
    fi
    
    # Configure unattended-upgrades
    cat > /etc/apt/apt.conf.d/50unattended-upgrades << 'EOF'
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};

Unattended-Upgrade::Package-Blacklist {
    "docker";
    "docker-ce";
};

Unattended-Upgrade::AutoFixInterruptedDpkg "true";
Unattended-Upgrade::MinimalSteps "true";
Unattended-Upgrade::InstallOnShutdown "false";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Remove-New-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "false";
Unattended-Upgrade::Automatic-Reboot-Time "02:00";
Unattended-Upgrade::SyslogEnable "true";
EOF
    
    # Enable automatic updates
    cat > /etc/apt/apt.conf.d/20auto-upgrades << 'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::Verbose "2";
EOF
    
    systemctl restart unattended-upgrades
    systemctl enable unattended-upgrades
    
    log "Unattended upgrades configured"
    add_score 5 5 "Unattended Upgrades"
}

#==============================================================================
# Check OS Patches
#==============================================================================
check_os_patches() {
    log "Checking OS patches..."
    
    apt-get update -qq
    
    local upgradable_count
    upgradable_count=$(apt list --upgradable 2>/dev/null | grep -c upgradable || echo "0")
    
    if [[ "$upgradable_count" -eq 0 ]]; then
        log "All OS packages are up to date"
        add_score 10 10 "OS Patches Current"
    else
        warn "$upgradable_count packages can be upgraded"
        log "Running security updates..."
        apt-get upgrade -y -qq
        add_score 10 10 "OS Patches Current (updated)"
    fi
}

#==============================================================================
# Disable Unused Services
#==============================================================================
disable_unused_services() {
    log "Disabling unused services..."
    
    local services=(
        "cups"
        "cups-browsed"
        "avahi-daemon"
        "bluetooth"
        " ModemManager"
    )
    
    for service in "${services[@]}"; do
        if systemctl list-unit-files | grep -q "^$service"; then
            systemctl stop "$service" 2>/dev/null || true
            systemctl disable "$service" 2>/dev/null || true
            log "Disabled: $service"
        fi
    done
    
    log "Unused services disabled"
}

#==============================================================================
# Secure File Permissions
#==============================================================================
secure_permissions() {
    log "Securing file permissions..."
    
    # Secure SSH directory
    chmod 700 /root/.ssh 2>/dev/null || true
    chmod 600 /root/.ssh/authorized_keys 2>/dev/null || true
    
    # Secure XDC data
    chmod 750 /root/xdcchain 2>/dev/null || true
    chmod 700 /root/xdcchain/keystore 2>/dev/null || true
    
    # Secure configs
    chmod 750 /opt/xdc-node 2>/dev/null || true
    chmod 600 /opt/xdc-node/configs/*.env 2>/dev/null || true
    
    # Remove world-writable permissions
    find /etc -type f -perm -002 -exec chmod o-w {} \; 2>/dev/null || true
    find /usr -type f -perm -002 -exec chmod o-w {} \; 2>/dev/null || true
    
    log "File permissions secured"
}

#==============================================================================
# Generate Security Report
#==============================================================================
generate_report() {
    mkdir -p /opt/xdc-node/reports
    
    local percentage=$((TOTAL_SCORE * 100 / MAX_SCORE))
    
    cat > "$SCORE_FILE" << EOF
{
  "timestamp": "$(date -Iseconds)",
  "totalScore": $TOTAL_SCORE,
  "maxScore": $MAX_SCORE,
  "percentage": $percentage,
  "rating": "$(if [[ $percentage -ge 90 ]]; then echo "Excellent"; elif [[ $percentage -ge 70 ]]; then echo "Good"; elif [[ $percentage -ge 50 ]]; then echo "Fair"; else echo "Poor"; fi)"
}
EOF
    
    cat >> "$REPORT_FILE" << EOF

==================================
Security Audit Report
==================================
Generated: $(date)
Server: $(hostname)
IP: $(hostname -I | awk '{print $1}')

TOTAL SCORE: $TOTAL_SCORE/$MAX_SCORE ($percentage%)

Rating: $(if [[ $percentage -ge 90 ]]; then echo "Excellent"; elif [[ $percentage -ge 70 ]]; then echo "Good"; elif [[ $percentage -ge 50 ]]; then echo "Fair"; else echo "Poor"; fi)

Recommendations:
$(if [[ $percentage -lt 90 ]]; then echo "- Review WARNINGS in the log above"; fi)
$(if [[ $percentage -lt 70 ]]; then echo "- Address CRITICAL issues immediately"; fi)
- Run this audit weekly: /opt/xdc-node/scripts/security-harden.sh
- Review logs: /var/log/auth.log, /var/log/audit/audit.log

==================================
EOF
    
    log ""
    log "=================================="
    log "Security Hardening Complete!"
    log "=================================="
    log "Score: $TOTAL_SCORE/$MAX_SCORE ($percentage%)"
    log "Rating: $(if [[ $percentage -ge 90 ]]; then echo "Excellent"; elif [[ $percentage -ge 70 ]]; then echo "Good"; elif [[ $percentage -ge 50 ]]; then echo "Fair"; else echo "Poor"; fi)"
    log ""
    log "Report saved to: $REPORT_FILE"
    log "Score file: $SCORE_FILE"
    log ""
    
    # Print rating color
    if [[ $percentage -ge 90 ]]; then
        echo -e "${GREEN}🟢 Production Ready${NC}"
    elif [[ $percentage -ge 70 ]]; then
        echo -e "${YELLOW}🟡 Minor improvements needed${NC}"
    elif [[ $percentage -ge 50 ]]; then
        echo -e "${YELLOW}🟠 Significant gaps, prioritize fixes${NC}"
    else
        echo -e "${RED}🔴 Not suitable for production${NC}"
    fi
}

#==============================================================================
# Main
#==============================================================================
main() {
    log "Starting Security Hardening..."
    
    check_root
    
    ssh_hardening
    setup_firewall
    setup_fail2ban
    setup_auditd
    sysctl_hardening
    setup_unattended_upgrades
    check_os_patches
    disable_unused_services
    secure_permissions
    
    generate_report
    
    log "Security hardening complete!"
    log ""
    log "IMPORTANT: Your SSH port has been changed to 12141"
    log "Update your connection: ssh -p 12141 root@<your-server-ip>"
}

main "$@"
