version: "2.0"
services:
  xdc-node:
    image: xinfinorg/xdposchain:v2.6.8
    expose:
      - port: 30303
        as: 30303
        to: [{global: true}]
      - port: 8545
        as: 8545
        to: [{global: true}]
    resources:
      cpu: {units: 4}
      memory: {size: 8Gi}
      storage: {size: 500Gi}
profiles:
  compute:
    xdc-node:
      resources:
        cpu: {units: 4}
        memory: {size: 8Gi}
        storage: {size: 500Gi}
  placement:
    global:
      pricing:
        xdc-node:
          denom: uakt
          amount: 1000
deployment:
  xdc-node:
    global:
      profile: xdc-node
      count: 1
