SKYNET_API_URL=https://skynet.xdcindia.com/api/v1
SKYNET_API_KEY=xdc_enq16v0Yb97kLuR5QaXdD45htoy7Rly6rvXgX8SAFNQwPycs
SKYNET_NODE_ID=bc47878e-d993-4cd0-a596-408f9c8f6fe6
SKYNET_NODE_NAME=xdc-nethermind-168-mainnet
SKYNET_ROLE=fullnode
