SKYNET_API_URL=https://skynet.xdcindia.com/api
SKYNET_API_KEY=xdc-netown-key-2026-prod
SKYNET_NODE_ID=88a75f54-9faf-46b7-b310-8b5b7184faef
SKYNET_NODE_NAME=xdc-stable-168-mainnet
SKYNET_ROLE=fullnode
